name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 14.x
          
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-node-modules
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install Dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
        working-directory: frontend
        
      - name: Build
        run: npm run build:ci
        working-directory: frontend
        
      - name: Lint
        run: npm run lint:ci
        working-directory: frontend
        
      - name: Test
        run: npm run test:ci
        working-directory: frontend

  backend:
    name: Backend
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Java 16
        uses: actions/setup-java@v2.3.0
        with:
          java-version: 16
          distribution: adopt
          architecture: x64
          cache: maven
      
      - name: Verify
        run: mvn --batch-mode --update-snapshots verify
        working-directory: backend
